In [82]:
import numpy as np
import pandas as pd

#### Datos

In [83]:
#t = [0, 10, 25, 65, 67, 125, 150]
#dt = [0, 10, 15, 40, 2, 58, 25]
#carga = [0, 150, 200, 50, 350, 90, 190]
#dt[0:5]

In [84]:
t = [0, 55, 75, 78, 95, 100]
dt = [0, 5, 50, 20, 3, 17, 5]
carga = [0, 250, 100, 50, 350, 120, 50]

#### Periodo

In [85]:
for i in range(1,8):
    for j in range(1,i):
        print(j)
    print("\n")



1


1
2


1
2
3


1
2
3
4


1
2
3
4
5


1
2
3
4
5
6




#### Load

In [86]:
for i in range(1,8):
    for j in range(1,i):
        print("A{}={}".format(j, carga[j]))
    print("\n")




A1=250


A1=250
A2=100


A1=250
A2=100
A3=50


A1=250
A2=100
A3=50
A4=350


A1=250
A2=100
A3=50
A4=350
A5=120


A1=250
A2=100
A3=50
A4=350
A5=120
A6=50




#### Change in load

In [87]:
change_load = []
for i in range(1,8):
    for j in range(1,i):
        print("A{}-A{}={}".format(j, j-1, carga[j]-carga[j-1]))
        change_load.append(carga[j]-carga[j-1])
    print("\n")
change_load = np.array([change_load])



A1-A0=250


A1-A0=250
A2-A1=-150


A1-A0=250
A2-A1=-150
A3-A2=-50


A1-A0=250
A2-A1=-150
A3-A2=-50
A4-A3=300


A1-A0=250
A2-A1=-150
A3-A2=-50
A4-A3=300
A5-A4=-230


A1-A0=250
A2-A1=-150
A3-A2=-50
A4-A3=300
A5-A4=-230
A6-A5=-70




In [88]:
change_load

array([[ 250,  250, -150,  250, -150,  -50,  250, -150,  -50,  300,  250,
        -150,  -50,  300, -230,  250, -150,  -50,  300, -230,  -70]])

#### Duration of period

In [89]:
for i in range(1,8):
    for j in range(1,i):
        print("M{}={}".format(j, dt[j]))
    print("\n")



M1=5


M1=5
M2=50


M1=5
M2=50
M3=20


M1=5
M2=50
M3=20
M4=3


M1=5
M2=50
M3=20
M4=3
M5=17


M1=5
M2=50
M3=20
M4=3
M5=17
M6=5




#### Time to End of Section

In [90]:
for i in range(1,8):
    for j in range(1,i):
        #print(i,j)
        #print("A{} = {}".format(j, carga[j]))
        if j+1==i:
            print("T=M{}={}".format(j, dt[j]))
        elif j+2 == i:
            print("T=M{}+M{}={}".format(j, j+1, sum(dt[j:i])))
        else:
            print("T=M{}+...+M{}={}".format(j, i-1, sum(dt[j:i])))
        #print(sum(dt[j:i]))

    print("\n")



T=M1=5


T=M1+M2=55
T=M2=50


T=M1+...+M3=75
T=M2+M3=70
T=M3=20


T=M1+...+M4=78
T=M2+...+M4=73
T=M3+M4=23
T=M4=3


T=M1+...+M5=95
T=M2+...+M5=90
T=M3+...+M5=40
T=M4+M5=20
T=M5=17


T=M1+...+M6=100
T=M2+...+M6=95
T=M3+...+M6=45
T=M4+...+M6=25
T=M5+M6=22
T=M6=5




In [91]:
y = []
for i in range(1,8):
    for j in range(1,i):
        print(sum(dt[j:i]))
        y.append(sum(dt[j:i]))
    print("\n")



5


55
50


75
70
20


78
73
23
3


95
90
40
20
17


100
95
45
25
22
5




In [92]:
y

[5,
 55,
 50,
 75,
 70,
 20,
 78,
 73,
 23,
 3,
 95,
 90,
 40,
 20,
 17,
 100,
 95,
 45,
 25,
 22,
 5]

#### K_T (interpolando desde curvas)

##### 1.69 V

In [93]:
v169 = pd.read_csv('1_69V.csv',sep=";",decimal=',')
v169

K  Minutos
0   0.555    1.059
1   0.562    1.197
2   0.567    1.326
3   0.574    1.456
4   0.588    1.594
..    ...      ...
62  3.971  190.196
63  4.157  203.409
64  4.378  219.133
65  4.611  234.699
66  4.884  251.614

[67 rows x 2 columns]

In [94]:
k169 =[]
k=0
for i in range(1,8):
    for j in range(1,i):
        print(np.interp(y[k], xp=v169['Minutos'], fp=v169['K']))
        k169.append(np.interp(y[k], xp=v169['Minutos'], fp=v169['K']))
        k+=1
    print("\n")



0.7039108910891089


1.7480073703606211
1.6569878048780489


2.083526169900538
1.9979236915049732
1.077050925925926


2.1428628846556417
2.049285178542312
1.1423665008291874
0.6413702422145329


2.412178981454224
2.327428990825688
1.476871724137931
1.077050925925926
1.0064054054054055


2.4946273620559336
2.412178981454224
1.563436770734784
1.183857142857143
1.1208076285240465
0.7039108910891089




In [95]:
k169=np.array([k169],dtype='float').reshape(change_load.shape)

Carga aleatoria

In [96]:
np.interp(1, xp=v169['Minutos'], fp=v169['K'])

0.555

##### 1.75 V

In [97]:
v175 = pd.read_csv('1_75V.csv',sep=";",decimal=',')
v175

K  Minutos
0   0.759    1.125
1   0.757    1.021
2   0.766    1.292
3   0.770    1.622
4   0.770    1.513
..    ...      ...
72  5.511  295.164
73  5.837  318.819
74  6.183  341.964
75  6.550  365.933
76  6.819  382.765

[77 rows x 2 columns]

In [98]:
k175 = []
k=0
for i in range(1,8):
    for j in range(1,i):
        print(np.interp(y[k], xp=v175['Minutos'], fp=v175['K']))
        k175.append(np.interp(y[k], xp=v175['Minutos'], fp=v175['K']))
        k+=1
    print("\n")



0.8846444444444445


1.9167816377171216
1.8290487663280117


2.2389430305073317
2.161282852091927
1.2488462078651685


2.2850247349823323
2.208941345019383
1.3179089159717767
0.8159463722397476


2.553740555127217
2.4695719609354922
1.6505270721925134
1.2488462078651685
1.179839222614841


2.633279719298246
2.553740555127217
1.7481353901070884
1.3613578104138853
1.2943148717948718
0.8846444444444445




In [99]:
k175=np.array([k175],dtype='float').reshape(change_load.shape)

Carga aleatoria

In [100]:
np.interp(1, xp=v175['Minutos'], fp=v175['K'])

0.759

#### Rated Amp Hrs

##### 1.69V

In [101]:
RAH = change_load*k169
RAH

array([[ 175.97772277,  437.00184259, -248.54817073,  520.88154248,
        -299.68855373,  -53.8525463 ,  535.71572116, -307.39277678,
         -57.11832504,  192.41107266,  603.04474536, -349.11434862,
         -73.84358621,  323.11527778, -231.47324324,  623.65684051,
        -361.82684722,  -78.17183854,  355.15714286, -257.78575456,
         -49.27376238]])

##### 1.75V

In [102]:
RAH = change_load*k175
RAH

array([[ 221.16111111,  479.19540943, -274.35731495,  559.73575763,
        -324.19242781,  -62.44231039,  571.25618375, -331.34120175,
         -65.8954458 ,  244.78391167,  638.43513878, -370.43579414,
         -82.52635361,  374.65386236, -271.3630212 ,  658.31992982,
        -383.06108327,  -87.40676951,  408.40734312, -297.69242051,
         -61.92511111]])